"""empty message

Revision ID: 1c81729310e9
Revises: 
Create Date: 2025-11-23 12:12:07.747252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c81729310e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lanzamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lanzamiento', sa.Integer(), nullable=False),
    sa.Column('timestamp_ms', sa.Float(), nullable=True),
    sa.Column('pressure_pa', sa.Float(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('altitude_asl_m', sa.Float(), nullable=True),
    sa.Column('altitude_rel_m', sa.Float(), nullable=True),
    sa.Column('vertical_speed_m_s', sa.Float(), nullable=True),
    sa.Column('maxAltitude_rel', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lanzamientos')
    # ### end Alembic commands ###
